### PR TITLE
Add Mayan EDMS as a sponsor

### PR DESCRIPTION
**Pull request by mayanedms**
Thank you for your work on Skulls. We used it on our fleet of ThinkPads.

### CODE REVIEW

**Comment by merge** [comment]
thank you very much for the support and the pull request. lgtm

**Comment by merge** [comment]
btw. which laptops do you use specifically?

**Comment by mayanedms** [comment]
We use the following models:

- T420 and T440p for main development and office work.
- T60 for remote support where CJIS or military CAC login is required and as consoles for server racks.
- X220 when our team travels or performs on-site support.
- T540p for running test and heavy CPU tasks (due to 4 core support). Experimental Skulls branch for T540p here if interested: https://github.com/mayan-edms/skulls/tree/t540p. We can provide one of each of the two T540p screen variants if necessary. We hope to make the T540p our main work model soon.
- Some remaining T400 that are being phased out.

Skulls is used as-is for the T440p. All other models use Coreboot compiled using Skulls files for baseline configuration. We have started using the Docker Coreboot SDK as provided by Skulls to build the new custom images.

**Comment by merge** [comment]
does wifi work with your T540p builds?

even if I haven't updated in a while, thank you very much for your support all these months!

I'm currently thinking about getting a W541 in order to add that to Skulls going forward, but in case your offer still stands, I'd try to do that with a T540p as well, even though the exact board is not part of coreboot currently. I'll leave reaching our via email to you in case it could still be helpful.

all the best

**Pull request merged**
